create table "public"."Chat" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "type" text,
    "from" bigint,
    "to" bigint,
    "agent_identity" text,
    "phone_number" text,
    "transcript" jsonb,
    "agent_id" text,
    "agent_metadata" jsonb,
    "metadata" jsonb
);


alter table "public"."Chat" enable row level security;

create table "public"."User" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text,
    "phone_number" text,
    "updated_at" timestamp with time zone default now(),
    "description" text,
    "type" text,
    "metadata" jsonb
);


alter table "public"."User" enable row level security;

CREATE UNIQUE INDEX "Chat_pkey" ON public."Chat" USING btree (id);

CREATE UNIQUE INDEX "User_pkey" ON public."User" USING btree (id);

alter table "public"."Chat" add constraint "Chat_pkey" PRIMARY KEY using index "Chat_pkey";

alter table "public"."User" add constraint "User_pkey" PRIMARY KEY using index "User_pkey";

alter table "public"."Chat" add constraint "Chat_from_fkey" FOREIGN KEY ("from") REFERENCES "User"(id) not valid;

alter table "public"."Chat" validate constraint "Chat_from_fkey";

alter table "public"."Chat" add constraint "Chat_to_fkey" FOREIGN KEY ("to") REFERENCES "User"(id) not valid;

alter table "public"."Chat" validate constraint "Chat_to_fkey";

grant delete on table "public"."Chat" to "anon";

grant insert on table "public"."Chat" to "anon";

grant references on table "public"."Chat" to "anon";

grant select on table "public"."Chat" to "anon";

grant trigger on table "public"."Chat" to "anon";

grant truncate on table "public"."Chat" to "anon";

grant update on table "public"."Chat" to "anon";

grant delete on table "public"."Chat" to "authenticated";

grant insert on table "public"."Chat" to "authenticated";

grant references on table "public"."Chat" to "authenticated";

grant select on table "public"."Chat" to "authenticated";

grant trigger on table "public"."Chat" to "authenticated";

grant truncate on table "public"."Chat" to "authenticated";

grant update on table "public"."Chat" to "authenticated";

grant delete on table "public"."Chat" to "service_role";

grant insert on table "public"."Chat" to "service_role";

grant references on table "public"."Chat" to "service_role";

grant select on table "public"."Chat" to "service_role";

grant trigger on table "public"."Chat" to "service_role";

grant truncate on table "public"."Chat" to "service_role";

grant update on table "public"."Chat" to "service_role";

grant delete on table "public"."User" to "anon";

grant insert on table "public"."User" to "anon";

grant references on table "public"."User" to "anon";

grant select on table "public"."User" to "anon";

grant trigger on table "public"."User" to "anon";

grant truncate on table "public"."User" to "anon";

grant update on table "public"."User" to "anon";

grant delete on table "public"."User" to "authenticated";

grant insert on table "public"."User" to "authenticated";

grant references on table "public"."User" to "authenticated";

grant select on table "public"."User" to "authenticated";

grant trigger on table "public"."User" to "authenticated";

grant truncate on table "public"."User" to "authenticated";

grant update on table "public"."User" to "authenticated";

grant delete on table "public"."User" to "service_role";

grant insert on table "public"."User" to "service_role";

grant references on table "public"."User" to "service_role";

grant select on table "public"."User" to "service_role";

grant trigger on table "public"."User" to "service_role";

grant truncate on table "public"."User" to "service_role";

grant update on table "public"."User" to "service_role";


