name: Deploy to Supabase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Check out code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js (required for Supabase CLI)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Supabase CLI requires Node.js v16+

      # Step 3: Install Supabase CLI
      - name: Install Supabase CLI
        run: npm install -g supabase

      # Step 4: Set up Supabase credentials
      - name: Set up Supabase credentials
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
        run: |
          # This sets up Supabase to use the project reference in the current directory
          supabase link --project-ref $SUPABASE_PROJECT_REF

      # Step 5: Deploy Edge Functions
      - name: Deploy Edge Functions
        run: supabase functions deploy --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}

      # Step 6: Apply Database Migrations
      - name: Deploy Database Migrations
        run: supabase db push --project-ref ${{ secrets.SUPABASE_PROJECT_REF }} --remote

      # Step 7: Additional Commands (e.g., storage or auth rules) as needed
      # - name: Deploy Additional Configurations
      #   run: supabase storage sync --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}